apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctr
  template:
    metadata:
      labels:
        app: doctr
    spec:
      containers:
        - name: doctr
          image: doctr
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/service_account/key.json
          envFrom:
            - configMapRef:
                name: doctr-config
          volumeMounts:
            - name: service-account-key
              mountPath: "/etc/service_account"
              readOnly: true
      volumes:
        - name: service-account-key
          secret:
            secretName: service-account-key
