apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-ocr-jobqueue
resources:
  - namespace.yml
  - deployment.yml
commonLabels:
  app.kubernetes.io/part-of: k8s-ocr-jobqueue
replacements:
  - source:
      kind: Deployment
      name: doctr
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
