---
name: "tagged-release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "macos-latest"
    steps:
      - name: Install make
        run: brew install make
      - uses: actions/checkout@v2
      - name: Build
        run: gmake
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Put version number in installer
        uses: bluwy/substitute-string-action@v1
        id: sub-installer
        with:
          _input-file: "./install.sh"
          _output-file: "./build/install.sh"
          _format-key: "%%key%%"
          version: "${{ steps.get_version.outputs.version }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*.tar.gz
            build/install.sh
            build/uninstall.sh
